### ISSUE TITLE
Use electron instead of phantomjs

### ISSUE THREAD

**Issue by fengmk2** [node-modules/webcamera#8]
https://npm.taobao.org/package/electron

Then we can publish 1.0.0 version.

**Comment by fengmk2** [comment]
- https://github.com/FWeinb/electron-screenshot-app
- https://github.com/FWeinb/electron-screenshot-service

**Comment by fengmk2** [comment]
http://electron.atom.io/docs/api/browser-window/#wincapturepagerect-callback

**Comment by fengmk2** [comment]
demo 还是挺简单的

``` js
'use strict';

const fs = require('fs');
const screenshot = require('electron-screenshot-service');
screenshot({
  url: 'https://npm.taobao.org',
  width : 1024,
  height : 768,
  page: true,
})
.then(img => {
  console.log(img);
  fs.writeFileSync(__dirname + '/out.png', img.data);
  screenshot.close();
});
```

![out](https://cloud.githubusercontent.com/assets/156269/19834969/86db7996-9eb1-11e6-9af9-6470dc28c642.png)

**Comment by shepherdwind** [comment]
electron 依赖 x11 ，大多数服务器都不带 x11 的，会截图失败的。

**Comment by fengmk2** [comment]
@shepherdwind 截图服务做到 qcloud 上，不需要线上服务器。

**Comment by ibigbug** [comment]
@shepherdwind 可以用 xvfb 的 https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md

**Comment by shepherdwind** [comment]
xvfb 这个没法安装到生产环节，主要我们 pe 不让安装自定义软件，这样不方便扩容。

**Comment by lizzie** [comment]
cli 中调用 electron 截图，会切窗口截图完又跳不回原窗口，这个怎么解？

**Comment by atian25** [comment]
现在可以换 https://github.com/GoogleChrome/puppeteer 了
